#!/usr/bin/env python3
"""Derive PyriteML task configs for a clean replay-generated sanding dataset.

Copies the two hand-written sanding1 configs (DP+FT and ACP) and retargets them
at a new zarr, adding the env knobs the eval script needs so the eval env matches
whatever env the dataset was generated in.

    python make_sanding_configs.py --dataset /store/real/jvclark/sanding_clean_smooth.zarr \
        --slug sanding_smooth --tool-kp 4000 --friction 0.3
"""
from __future__ import annotations

import argparse
import os
import re

CFG_DIR = "/store/real/jvclark/PyriteML/diffusion_policy/config/task"
BASE = {"dp": "sanding1_dp_ft_s8h8.yaml", "acp": "sanding1_acp_s8h8.yaml"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset", required=True)
    ap.add_argument("--slug", required=True, help="e.g. sanding_smooth")
    ap.add_argument("--tool-kp", type=float, required=True)
    ap.add_argument("--friction", type=float, required=True)
    ap.add_argument("--max-ticks", type=int, default=30000)
    ap.add_argument("--note", default="")
    args = ap.parse_args()

    for kind, base in BASE.items():
        src = os.path.join(CFG_DIR, base)
        s = open(src).read()
        old_name = base[:-5]
        new_name = f"{args.slug}_{'dp_ft' if kind == 'dp' else 'acp'}_s8h8"

        # Line-anchored: a plain str.replace of "task: sanding1" matches the
        # "#   task: sanding1" comment first and burns the count=1, leaving the
        # real field untouched -- which then feeds hydra's run-dir template and
        # the wandb group with the wrong task.
        s = re.sub(r"(?m)^name: .*$", f"name: {new_name}", s, count=1)
        s = re.sub(r"(?m)^task: \S+$", f"task: {args.slug}", s, count=1)
        s = re.sub(r"(?m)^#   task: \S+$", f"#   task: {args.slug}", s, count=1)
        s = re.sub(r"(?m)^dataset_name: \S+$", f"dataset_name: {args.slug}", s, count=1)
        s = re.sub(r"(?m)^task_name: &task_name \S+$",
                   f"task_name: &task_name {args.slug}", s, count=1)
        s = s.replace("dataset_path: /store/real/jvclark/sanding_1.zarr",
                      f"dataset_path: {args.dataset}", 1)
        s = re.sub(r"max_ticks: \d+", f"max_ticks: {args.max_ticks}", s, count=1)

        # eval must rebuild the env the demos were generated in
        s = s.replace('''  extra_args:
    - "--video-episodes"
    - "3"''', f'''  extra_args:
    - "--video-episodes"
    - "3"
    - "--tool-kp"
    - "{args.tool_kp:.0f}"
    - "--friction"
    - "{args.friction}"''', 1)

        header = (f"# AUTO-DERIVED from {base} by make_sanding_configs.py\n"
                  f"# Dataset generated by gen_sanding_clean.py with "
                  f"tool_kp={args.tool_kp:.0f}, friction={args.friction}.\n"
                  f"# Eval MUST use the same two knobs (they are in eval.extra_args below)\n"
                  + (f"# {args.note}\n" if args.note else ""))
        s = s.replace("\n", "\n", 1)
        lines = s.split("\n")
        s = lines[0] + "\n\n" + header + "\n".join(lines[1:])

        dst = os.path.join(CFG_DIR, new_name + ".yaml")
        open(dst, "w").write(s)
        print(f"wrote {dst}")


if __name__ == "__main__":
    main()
